const products = [
    {
      id: "B1",
      brand: "Barenbliss",
      name: "BNB barenbliss Better Than Magic Eyeliner Waterproof Korea Make Up Eyeliner Pensil Tahan Lama-Hitam",
      image: "aset/barenbliss_eye_product_1.png",
      description: "lorem ipsum",
      hashtag: "#lorem",
      price: "Rp 40.500",
      actualPrice: 40500,
      rating: "4.5",
      offer: "Diskon",
      stock: "Tersedia",
      gender: "Women",
      categories: "Make up",
      age: "<18",
      skinType: "Dry",
      skinProblem: "Acne",
      productType: "Cleanser",
      isWishlist: "True"
    },
    {
      id: "B2",
      brand: "Barenbliss",
      name: "BNB barenbliss Korean Like A Pro! Shockproof Durabrow Pomade Waterproof Smudgeproof Long Lasting",
      image: "aset/barenbliss_eye_product_2.png",
      description: "lorem ipsum",
      hashtag: "#lorem",
      price: "Rp 62.100",
      actualPrice: 62100,
      rating: "4",
      offer: "Diskon",
      stock: "Tersedia",
      gender: "Women",
      categories: "Make up",
      age: "<18",
      skinType: "Oily",
      skinProblem: "Dark Spots",
      productType: "Toner",
      isWishlist: "True"
    },
    {
      id: "B3",
      brand: "Barenbliss",
      name: "BNB barenbliss Korean Bloomatte True Beauty Inside Cushion 24H Full Coverage",
      image: "aset/barenbliss_face_2_png_1.png",
      description: "lorem ipsum",
      hashtag: "#lorem",
      price: "Rp 143.100",
      actualPrice: 143100,
      rating: "4.5",
      offer: "Cashback",
      stock: "Preorder",
      gender: "Women",
      categories: "Make up",
      age: "18-40",
      skinType: "Dry",
      skinProblem: "Dark Spots",
      productType: "Cleanser",
      isWishlist: "True"
    },
    {
      id: "B4",
      brand: "Barenbliss",
      name: "BNB barenbliss Machi Peachy Micellar Water - Mineral Oil Freea",
      image: "aset/barenbliss_skin_face_2.png",
      description: "lorem ipsum",
      hashtag: "#lorem",
      price: "Rp 49.500",
      actualPrice: 49500,
      rating: "5",
      offer: "Cashback",
      stock: "Tersedia",
      gender: "Men",
      categories: "Make up",
      age: "18-40",
      skinType: "Dry",
      skinProblem: "Acne",
      productType: "Toner",
      isWishlist: "False"
    },
    {
      id: "S1",
      brand: "Somethinc",
      name: "Holyshield! UV Watery Sunscreen Gel SPF 50+ PA++++",
      image: "aset/somethinc_holyshield1.png",
      description: "Somethinc Sunscreen Gel dengan SPF 50+ PA++++ & teknologi Encapsulated UV Filter yang memberikan proteksi lebih maksimal dari sinar UVA & UVB. Somethinc SPF 50 ini dilengkapi dengan proteksi terhadap Polusi, Blue-Light, & Infra-Red untuk mencegah tanda penuaan dini. Dengan Snowflake Molecules yang memberikan sensasi dingin & menyerap langsung seperti air, nyaman digunakan sepanjang hari, bebas alkohol, tidak lengket, serta no white-cast! Bikin betah & gak ada alasan lagi untuk gak pakai sunscreen Somethinc!",
      hashtag: "#HolyShield #SunTerror #SunscreenSensasiSalju",
      price: "Rp 125.000",
      actualPrice: 125000,
      rating: "4.5",
      offer: "Grosir",
      stock: "Tersedia",
      gender: "Men",
      categories: "Make up",
      age: "18-40",
      skinType: "Oily",
      skinProblem: "Acne",
      productType: "Cleanser",
      isWishlist: "False"
    },
    {
      id: "S2",
      brand: "Somethinc",
      name: "Glowing Up Sunscreen Stick SPF 50++ PA ++++",
      image: "aset/somethinc_glowingUp.png",
      description: "LOREM IPSUM",
      hashtag: "#HolyShield #SunTerror #SunscreenSensasiSalju",
      price: "Rp 125.000",
      actualPrice: 125000,
      rating: "4",
      offer: "Grosir",
      stock: "Tersedia",
      gender: "Men",
      categories: "Make up",
      age: ">40",
      skinType: "Oily",
      skinProblem: "Acne",
      productType: "Toner",
      isWishlist: "False"
    },
    {
      id: "S3",
      brand: "Somethinc",
      name: "Holyshield! Sunscreen Comfort Corrector Serum SPF 50+ PA++++",
      image: "aset/somethinc_comfortCorrector.png",
      description: "LOREM IPSUM",
      hashtag: "#HolyShield #SunTerror #SunscreenSensasiSalju",
      price: "Rp 69.000",
      actualPrice: 69000,
      rating: "4.5",
      offer: "Diskon",
      stock: "Preorder",
      gender: "Men",
      categories: "Skin Care",
      age: ">40",
      skinType: "Dry",
      skinProblem: "Dark Spots",
      productType: "Cleanser",
      isWishlist: "True"
    },
  ];
  
  export { products };